version: "3.8"

services:
  app:
    container_name: template-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    command: npm run start
